=== DarcanoS/Tendencias_Proyecto/XML/MicroSerFor.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="App">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Entidades" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <!-- Nombre de la Tabla de la base de datos -->
                            <xs:element name="nombreEntidad" type="xs:string" />
                            <!-- Atributo o Columna de la Tabla de la Base de Datos -->
                            <xs:element name="atributo" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombreAtributo" type="xs:string" />
                                        <xs:element name="tipoAtributo" type="xs:string" />
                                        <xs:element name="restricionAtributo" type="xs:string"
                                            minOccurs="0"
                                            maxOccurs="unbounded" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <!-- El atributo primario es la llave de la entidad, debe tener minimo
                            una, puede tener llaves compuestas -->
                            <xs:element name="atributoPrimario" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombreAtributo" type="xs:string" />
                                        <xs:element name="tipoAtributo" type="xs:string" />
                                        <xs:element name="restricionAtributo" type="xs:string"
                                            maxOccurs="unbounded" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <!-- Este vendrÃ­a a ser el EndPoint -->
                            <xs:element name="Servicio" minOccurs="0" maxOccurs="4">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="tipoServicio">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="update" />
                                                    <xs:enumeration value="create" />
                                                    <xs:enumeration value="delete" />
                                                    <xs:enumeration value="readAll" />
                                                    <xs:enumeration value="readOne" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <!-- Nombre del EndPoint -->
                                        <xs:element name="nombreServicio" minOccurs="0">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <!-- No puede tener espacios, ya que el nombre
                                                    del EndPoint es el que va a aparecer con la URL -->
                                                    <xs:pattern value="[^\s]*" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Conexion" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="url" type="xs:string" />
                            <xs:element name="puerto" type="xs:integer" />
                            <xs:element name="database" type="xs:string" />
                            <xs:element name="usuario" type="xs:string" />
                            <xs:element name="password" type="xs:string" />
                            <xs:element name="controlador" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== DarcanoS/Tendencias_Proyecto/Front/XML/vacio.xml
<?xml version="1.0"?>
<App 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="./MicroSerFor.xsd">
<nombreEntidad>sxfh</nombreEntidad>
<nombreAtributo>shsr</nombreAtributo>
<TipoAtributo>String</TipoAtributo>
<nombreAtributo>srhsr</nombreAtributo>
<TipoAtributo>String</TipoAtributo>
<TipoServicio>update</TipoServicio>
<nombreServicio>srhsrh</nombreServicio>
<url>srhrs</url>
<puerto>53</puerto>
<database>srhys</database>
<usuario>srhrh</usuario>
<password>srhsryh</password>
<controlador>srhsrh</controlador>
</App>


<?xml version="1.0"?>
<App xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="./MicroSerFor.xsd">
 <Entidades>
     <nombreEntidad>fhdfh</nombreEntidad>
     <TipoAtributo>String</TipoAtributo>
     <TipoAtributo>String</TipoAtributo>
     <TipoServicio>update</TipoServicio>
     <nombreServicio>dghdgh</nombreServicio>
     <url>dghdtgh</url>
     <puerto>876</puerto>
     <database>wstgw</database>
     <usuario>sgsg</usuario>
     <password>sgsfdg</password>
     <controlador>sergtwe</controlador>
    </Entidades>
        <atributo>
            <nombreAtributo>dghdth</nombreAtributo>
            <nombreAtributo>dghdghd</nombreAtributo>
        </atributo></App>

=== DarcanoS/Tendencias_Proyecto/XML/MicroSer.xml
<?xml version="1.0"?>

<!-- xmlns="http://www.w3schools.com"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="./ MicroSerFor.xsd" -->
<App
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="./MicroSerFor.xsd">
    <Entidades>
        <nombreEntidad>Producto</nombreEntidad>
        <atributo>
            <nombreAtributo>Nombre</nombreAtributo>
            <tipoAtributo>VARCHAR(20)</tipoAtributo>
            <restricionAtributo>NOT NULL</restricionAtributo>
            <restricionAtributo>NOT NULL</restricionAtributo>
        </atributo>
        <atributoPrimario>
            <nombreAtributo>ID</nombreAtributo>
            <tipoAtributo>Integer</tipoAtributo>
            <restricionAtributo>NOT NULL</restricionAtributo>
        </atributoPrimario>
        <Servicio>
            <tipoServicio>create</tipoServicio>
            <nombreServicio>crearProducto</nombreServicio>
        </Servicio>
        <Servicio>
            <tipoServicio>readAll</tipoServicio>
            <nombreServicio>ObtenerProductos</nombreServicio>
        </Servicio>
    </Entidades>
    <Entidades>
        <nombreEntidad>Inventario</nombreEntidad>
        <atributoPrimario>
            <nombreAtributo>ID</nombreAtributo>
            <tipoAtributo>Integer</tipoAtributo>
            <restricionAtributo>NOT NULL</restricionAtributo>
        </atributoPrimario>
        <atributoPrimario>
            <nombreAtributo>IdProducto</nombreAtributo>
            <tipoAtributo>Integer</tipoAtributo>
            <restricionAtributo>NOT NULL</restricionAtributo>
        </atributoPrimario>
        <Servicio>
            <tipoServicio>create</tipoServicio>
            <nombreServicio>crearInventario</nombreServicio>
        </Servicio>
        <Servicio>
            <tipoServicio>update</tipoServicio>
            <nombreServicio>actualizarInventario</nombreServicio>
        </Servicio>
        <Servicio>
            <tipoServicio>delete</tipoServicio>
            <nombreServicio>eliminarInventario</nombreServicio>
        </Servicio>
    </Entidades>
    <Conexion>
        <url>localhost</url>
        <puerto>22</puerto>
        <database>BasePruebas</database>
        <usuario>admin</usuario>
        <password>1234</password>
        <controlador>./aqui/alla</controlador>
    </Conexion>
</App>
